### ISSUE TITLE
SpiLoader 编译报错

### ISSUE THREAD

**Issue by suifengrumeng163** [liuyueyi/SilverSpi#1]
您好，我下载源码后编译报错
class SpiLoader<T>类第一行中

 private static final SelectorWrapper DEFAULT_SELECTOR = **new SelectorWrappe**r(new DefaultSelector(), String.class);
错误提示:
SelectorWrapper( ) 
in SelectorWrapper cannot be applied
to
(com.yihui.silver.spi.selector.DefaultSelector,
java.lang.Class<java.lang.String>)
![image](https://user-images.githubusercontent.com/29506122/27254050-befb1dde-53b2-11e7-824d-1b3a3a3e3a73.png)

**Comment by liuyueyi** [comment]
看一下 lombok 的插件有没有安装，因为使用了lombok, 如果你是idea的话，需要安装一下对应的插件

```
@Getter
@Setter
@ToString
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
public class SelectorWrapper {

    /**
     * 具体的选择器
     */
    private ISelector selector;


    /**
     * 具体选择器对应的条件类型
     */
    private Class conditionType;

}
```
